version: "3.7"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: manager-frontend
        container_name: manager-frontend
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - manager-frontend

    nginx:
        image: nginx:alpine
        container_name: manager-frontend-nginx
        restart: unless-stopped
        ports:
            - 8010:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - manager-frontend

networks:
    manager-frontend:
        driver: bridge
